// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNgl9JmGAi62Z6-uuKaJxl-egmOe83mWo',
    appId: '1:697316535739:web:0f2da07f7ab3687224689e',
    messagingSenderId: '697316535739',
    projectId: 'hire-nova-ai-707',
    authDomain: 'hire-nova-ai-707.firebaseapp.com',
    storageBucket: 'hire-nova-ai-707.firebasestorage.app',
    measurementId: 'G-6B13CH88J5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDdQDyC4DPfD4SfHV0RPCV0RglCcRHJNE',
    appId: '1:697316535739:android:579e40e588f6fbae24689e',
    messagingSenderId: '697316535739',
    projectId: 'hire-nova-ai-707',
    storageBucket: 'hire-nova-ai-707.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMcedScvRTErsoXR5s6VnqbZ6k8Cax6Ag',
    appId: '1:697316535739:ios:944cda95ba9ee04c24689e',
    messagingSenderId: '697316535739',
    projectId: 'hire-nova-ai-707',
    storageBucket: 'hire-nova-ai-707.firebasestorage.app',
    iosClientId: '697316535739-d2t2inavt77m6bts2hi1nc37cdi9mel5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hirenovaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMcedScvRTErsoXR5s6VnqbZ6k8Cax6Ag',
    appId: '1:697316535739:ios:944cda95ba9ee04c24689e',
    messagingSenderId: '697316535739',
    projectId: 'hire-nova-ai-707',
    storageBucket: 'hire-nova-ai-707.firebasestorage.app',
    iosClientId: '697316535739-d2t2inavt77m6bts2hi1nc37cdi9mel5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hirenovaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNgl9JmGAi62Z6-uuKaJxl-egmOe83mWo',
    appId: '1:697316535739:web:620d16e828dab20424689e',
    messagingSenderId: '697316535739',
    projectId: 'hire-nova-ai-707',
    authDomain: 'hire-nova-ai-707.firebaseapp.com',
    storageBucket: 'hire-nova-ai-707.firebasestorage.app',
    measurementId: 'G-655C7DDR2S',
  );

}